Repository vanholler/js_runtime_engine, pull requests merged in 2025-10, with the labels that each got.

#5 Fixed the problems with variable history
  src/App.vue
Labels: hacktoberfest, JS

#13 Global Scope & Console Fixes
  package-lock.json
  package.json
  src/App.vue
Labels: bug, hacktoberfest, hacktoberfest2025, UI, JS

#16 Adding Settings options and update npm packages
  src/App.vue
Labels: enhancement, hacktoberfest, hacktoberfest2025, UI, JS
